### ISSUE TITLE
[BUG] Non breakable permission loop in add picture to POI

### ISSUE THREAD

**Issue by kaleng** [jawg/osm-contributor#109]
**Description:**

If permission to take pictures is declined, there is no way to break out of the permission request loop.

**Steps to reproduce:**

1. Create POI
1. Highlight POI
1. "Add Picture"
1. Click "+" for adding a picture
1. Permission request appears
1. Decline permission
1. permissionNotEnabled dialog appears
1. click OK
1. restart from "Permission request appears"

**Expected behavior:**
When the permission is declined, the user should have a choice to continue without it or try to grant the permission again

**Actual behavior:**
Whe the permission is declined, the user gets asked for the permission again. There is no other way to exit this loop than closing the app.

**Version:**
master @ 64c0ac3b0ccf8654e916089119ece88ad369147e

**Comment by loicortola** [comment]
@kaleng thanks, will fix this soon.

**Comment by kaleng** [comment]
Just retested with master @ f0df2a4. This was fixed. Thanks again @Capaldijo!
