### ISSUE TITLE
[BUG] Clicking "Find my location" Button returns to initial location

### ISSUE THREAD

**Issue by kaleng** [jawg/osm-contributor#110]
**Description:**
If no location provider is enabled or able to return a location, osm-contributor returns the camera view to the initial location (currently Paris) - which is kind of annoying if you just scrolled all the way to some country.

**Steps to reproduce:**

1. Disable location services
1. Scroll to some location other than the Eiffel Tower
1. Click the "Find my location" button
1. Camera view gets reset to the Eiffel Tower

**Expected behavior:**
If a location is found it should move to that location, otherwise it should not change the view.

**Actual behavior:**
Camera view gets moved to the initial location as defined in build.gradle CENTER_LAT/CENTER_LNG

**Version:**
master @ 64c0ac3

**Comment by loicortola** [comment]
@kaleng thanks.
This bug is "non-critical", but will also solve it asap.

**Comment by kaleng** [comment]
Just retested with master @ f0df2a4. Seems good to me. Thanks @Capaldijo!
