### ISSUE TITLE
[BUG] Save modifications: comment disappears on failed upload

### ISSUE THREAD

**Issue by kaleng** [jawg/osm-contributor#112]
**Description:**
Clicking the checkmark in the "Save modifications" dialog clears the comment textfield when no credentials are given.

**Steps to reproduce:**

1. do not give login credentials
1. Create / modify some POIs
1. Choose "Save..." from the menu
1. Add a comment
1. Click the checkmark

**Expected behavior:**
comment textfield should not be modified

**Actual behavior:**
comment textfield is cleared

**Version:**
master @ 64c0ac3

**Comment by loicortola** [comment]
Thanks @kaleng,
will look into it ASAP.
A new release will be coming up monday for sure.

**Comment by kaleng** [comment]
Just retested with master @ f0df2a41e4d6056cbf8687b11c26234d78753bbb. Seems good to me. Thanks @Capaldijo!
