### ISSUE TITLE
[BUG] Camera zoom gets resettet on "Find my Location"

### ISSUE THREAD

**Issue by kaleng** [jawg/osm-contributor#113]
**Description:**
When there is an gps fix and the "Find my Location" button is clicked, the camera zoom gets resettet to the initial zoom level.
This is kind of related to #110 .

**Steps to reproduce:**

1. Have gps fix
1. scroll around on the map
1. change the zoom level
1. click "Find my Location"-button

**Expected behavior:**
Camera view should be moved to current location, zoom level **should not** be changed.

**Actual behavior:**
Camera view gets moved to current location, zoom level **is** changed to initial zoom level.

**Version:**
master @ 64c0ac3

**Comment by loicortola** [comment]
Hi @kaleng ,
this issue should be resolved in the next version.
I will close this issue now :)
