### ISSUE TITLE
[Jungle Bus] bus_stop: Yes and No are selected for bench

### ISSUE THREAD

**Issue by versat** [jawg/osm-contributor#141]
I opened some bus stops to look for details that i could add (Selected bus stop and clicked Edit).
For some of the bus stops the data seemed reasonable.
Then i got this:
![junglebus_yesno](https://user-images.githubusercontent.com/7264306/33202734-e6aa1010-d0fd-11e7-9f6a-1b52453ceff2.png)
I closed the Edit form and reopened it, the error was still there.
After closing the app and opening it again and selecting the very same bus stop where the error occurred before, the error was not shown any longer, but the correct entry was selected.
So it seems to be a sporadic problem, not related to a specific combination of entries for the bus stop, but maybe it has something to do what bus stops where selected before and in which order. I am not able to reproduce the very same steps since i do not remember which bus stops i selected in which order.

**Steps to reproduce:**
Select a bus stop and click on Edit.
Maybe repeat selecting bus stops and clicking on Edit.
Scroll to "bench" and maybe find "Yes" and "No" both be selected.

**Expected behavior:**
Either Yes or No or undefined should be selected, but never two or more of them at the same time.

**Actual behavior:**
Yes and No were both selected.

**Stacktrace (If it's a crash):**
No crash, no stack trace.

**Environment:**
Sony Xperia XZ, Android 7.1.1 (official firmware).

**Version:**
Jungle Bus v1.2.5

**Comment by overflorian** [comment]
Thanks for the feedback @versat, we will have a look and keep you updated

**Comment by overflorian** [comment]
@nicolasfavier @Hugoo13 any feedback regarding this issue guys?
Thanks

**Comment by nicolasfavier** [comment]
It should be fix on the v3.0.17
