### ISSUE TITLE
Trackers detected ?

### ISSUE THREAD

**Issue by GilBr** [jawg/osm-contributor#147]
Exodus Privacy has detected 3 trackers in Osm Contributor. Report here: https://reports.exodus-privacy.eu.org/reports/858/
Is it your choice ? Necessary ?

**Comment by loicortola** [comment]
Hi @GilBr ,

we already had discussions with the community on this topic
https://twitter.com/LoicOrtola/status/942709341685248000

The "trackers" are tracking anonymous data that I think are essential to us.

Let me explain you how it helps :
 * They allow us to get stack traces when your app crashes and fix all the bugs of the app
 * They allow us to understand the way you use OSM Contributor, and what features are left apart, or most used
 * They allow us to get usage statistics on the app. How many people use it, from which countries etc, which allow us to ask for relevant contributions for translations for instance.

They do not gather personal data (well they are always playing on the word "personal" for sure, but we collect data to detect trends, not to track a single person)

If all users were like you (giving useful feedback, requesting features etc...) we wouldn't need it.
Unfortunately, it is not the case :)

I totally understand if you want to drop them, and I think we used to have a dedicated flavor that takes out all trackers. It needs to be built separately though and it is not trivial to maintain :)

I hope my explanations are reassuring. I know it is not perfect, but without it there is no way OSM Contributor would have been even close to the app you are playing with!

Happy new year by the way!

Loïc

**Comment by GilBr** [comment]
It's ok for me. I understand the problems with Android apps development.
I'll relay your explanations.
Thanks for your immediate response !

**Comment by loicortola** [comment]
No worries :) always a pleasure
