### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by Hugoo13** [jawg/osm-contributor#15]
Search address, places ... with Nominatim

**Comment by stephan75** [comment]
or any other framework / engine listed at http://wiki.openstreetmap.org/wiki/Search_engines

**Comment by stephan75** [comment]
@sdesprez and @loicortola 

I am planning a crowd mapping party with local OSM enthusiasts to improve tagging situation in our relevant area, with the help of android devices.

So is there any chance that we could use a fresh release of OSM-Contributor app with new code base since December 2015, and maybe even one or two solved issues (like this one) from current open github issues according to extended usability?

That would be really great!

**Comment by loicortola** [comment]
Hi @stephan75 
thanks for the comments. 
Yes you could. Right now, @Hugoo13 and @tommybuonomo are working on a new release with much performance improvement (most important feature being the switch to mapbox-gl).
We have a great roadmap (vector maps, offline regions, search), and the milestone is set to early september 2016.

I think we may have a working beta in the end of june, with the new maps library and the search feature. Want to be a part of it?

**Comment by stephan75** [comment]
@loicortola 
Ohh that are wonderful news!  Although I have almost no programming skills myself to create real pull requests or similar, I would like to take part in development in any possible way. At least I could do some translations on Transifex. And I am very familiar with OSM's data structure.

In the case that "being a part of it" means the availibility of any beta apk file or official beta testing app via google play services, I can also dive into it. Tell me when you are even aiming at any beta test for a group of experienced OSM users that can be made public via selected OSM channels.
But whole project control should remain to the developers, I don't want to be too much eager to that and get in a wrong way.

**Comment by loicortola** [comment]
@stephan75 just launched the beta (yeah I know, kind of late).
We just wanted to have all the features ready of the future v3.
Still interested into beta-testing? If yes, let's MP on twitter (@jawgio).

**Comment by stephan75** [comment]
Yep, still interested in beta testing ... but I have no twitter account.

Is there another way to get beta status?
You can contact me best via OSM messaging system,
where http://www.openstreetmap.org/user/stephan75 is my user profile.

**Comment by loicortola** [comment]
Hi @stephan75 ,
actually, the only thing we need is not a twitter account, but rather a gmail account (as the beta is on the play store).
I'll send you a MP on OSM
