### ISSUE TITLE
Loading screen never ending

### ISSUE THREAD

**Issue by overflorian** [jawg/osm-contributor#159]
**Description:**
Hi,
With the last update version 3.0.15, while opening the app, the loading screen is never ending. It means the users can't contribute at all.
4 different users gave me the same feedback. They have different phones and android version, even language config. I did not face this issue on my own phone.
Please have a look at these screenshots https://photos.app.goo.gl/TmpssUmp7fbUUGPG3

**Comment by nicolasfavier** [comment]
It's an error on sql update.
It fix on the 3.0.16 release
