### ISSUE TITLE
http://osm.jawg.io is down

### ISSUE THREAD

**Issue by habi** [jawg/osm-contributor#179]
The README mentions a beta test instance at http://osm.jawg.io
I cannot load this page, neither on iOS or Ubuntu.
Is it down?

**Comment by loicortola** [comment]
Hello @habi yes because this platform was not really used anymore, we put it down.
It gave the ability to make your own version of the app.
Now, we have implemented custom presets instead.

**Comment by habi** [comment]
Then you should probably remove it from the README :)
