### ISSUE TITLE
Question: Why use legacy MapBox Android SDK

### ISSUE THREAD

**Issue by westnordost** [jawg/osm-contributor#50]
I read in the [openstreetmap wiki](http://wiki.openstreetmap.org/wiki/OSM_Contributor_Mapping_Tool) that osm-contributor _"uses a fork of the legacy Mapbox Android SDK"_.

I am interested to know why. Does anyone know?

**Comment by loicortola** [comment]
Hi @westnordost .
Sorry for the delay.
The answer is: we don't anymore ;)
On the develop branch, we are preparing an awesome major release upgraded with the latest Mapbox Gl SDK, vector tiles, and new UX.
It really makes an awesome difference and I hope you will like it.
Would you be interested in getting an early Release Candidate to give us your feedback?
We are planning to release the new app in August.

**Comment by westnordost** [comment]
Ah, so the info is outdated, ok. The background of my question was because I was hoping that perhaps the old version of Mapbox SDK would not have this [telemetry](https://www.mapbox.com/tos/#[TuMSTSwp]) built-in that the app may not control.

I am also currently developing an app for contributing data to openstreetmap which also displays a map. I am aiming to use [tangram-es](https://github.com/tangrams/tangram-es) for the map rendering, but it is not quite as mature as I hoped it to be (in regards to map markers and map overlays)

> Would you be interested in getting an early Release Candidate to give us your feedback?
Okay, sure. I'd be happy to help with some feedback.

I close this issue as the question has been answered.
