### ISSUE TITLE
Allow to select a "preset" among an open marketplace of presets for contributors

### ISSUE THREAD

**Issue by loicortola** [jawg/osm-contributor#52]
Many people requested custom versions for their Mapping parties, with custom type presets.
Well, we want to make it easier for you and create a simple and open marketplace for presets.
This will be released along with the next major version, coming August 2016.

Contributions are welcome!

**Comment by gleberre** [comment]
An example of awaited "tree inventory preset" would be the following :

- POI type : natural = tree

- Attributes : species (string), age (integer), a picture of the tree
