### ISSUE TITLE
Tags not visible on POI edition

### ISSUE THREAD

**Issue by GilBr** [jawg/osm-contributor#54]
**Description**
Tags aren't visible with the POI edition tool

**Steps and behaviour**
1. Refresh the POI
2. Select the POI
3. Use the edition tool "Editer le poi"
=> No tags are visible
=> When I use "Ajouter un tag", tag isn't visible too

**Environment:**
Smartphone : Wiko Rainbow 4G – Android 4.4.2

**Version:**
3.0.0-beta1 (2016-08-22) + "Preset par défaut" profile
I update the 2.2 version with the new one.

**Comment by Hugoo13** [comment]
We will try to reproduce this issue. 
Are you in expert mode ? 
Sometimes, some tags are not showing in "normal mode".

We will keep you inform !

**Comment by GilBr** [comment]
Thanks for your response.
I use the expert mode and I have the same behaviour without ...

**Comment by Hugoo13** [comment]
I can't find a POI with no tag. 
It would be helpful to know which POI types are concerned by this issue.

**Comment by GilBr** [comment]
I've tried the app in Nantes on this [POI](https://www.openstreetmap.org/node/3763108670).
(I dont't know how to obtain the bbox, but if you explain, I can try)
And it's the same for all the POI downloaded on my app in this area.
(as shown on screenshots)
A problem with the app on my smartphone ? I can reinstall it if needed.

![screenshot_2016-08-24-14-20-03](https://cloud.githubusercontent.com/assets/21213907/17935310/1d328ec8-6a1b-11e6-98e6-ade7a6d24e77.png)
![screenshot_2016-08-23-21-54-56](https://cloud.githubusercontent.com/assets/21213907/17935313/2089e8d2-6a1b-11e6-9f52-9e07ff4cd81d.png)

**Comment by GilBr** [comment]
I tried to uninstall et reinstall directly the v3.0.0-beta1 and it's still the same behaviour ...
No tags on POI Edition. 
In the expert mode, with the "Gérer les types de Poi" fonction, I correctly have the tags and I can edit them.

**Comment by Hugoo13** [comment]
Thank you for your feedback.
I will try to reproduce this issue and find a solution.

I will keep you inform !

**Comment by Hugoo13** [comment]
We are going to deploy a new beta (beta.2). Now, you can add a tag from edit poi page.
Unfortunately, I wasn't able to reproduce the problem with tags visibility in POI edition.
Please try the new version (available in a few hours on the Play Store). If the problem persists, keep me informed here #56.

![screenshot_20160825-134702](https://cloud.githubusercontent.com/assets/3592767/17970127/803f95fa-6ad5-11e6-8e7d-5f34ea3cc010.png)

**Comment by GilBr** [comment]
Wonderfull ! I'll try this evening.
