### ISSUE TITLE
Tags aren't visible with the POI edition tool

### ISSUE THREAD

**Issue by Hugoo13** [jawg/osm-contributor#56]
Description
Tags aren't visible with the POI edition tool

Steps and behaviour
1. Refresh the POI
2. Select the POI
3. Use the edition tool "Editer le poi"
=> No tags are visible

Environment:
Smartphone : Wiko Rainbow 4G – Android 4.4.2

Version:
3.0.0-beta1 (2016-08-22) + "Preset par défaut" profile
I update the 2.2 version with the new one.

From issue #54

**Comment by GilBr** [comment]
I made the update 3.0.0-beta2 but now the app crash at every launch ...
I send the report on the Play Store (Is it usefull ?)
About my smartphone, I use [AppMgr III](https://play.google.com/store/apps/details?id=com.a0soft.gphone.app2sd) to freeze some Google apps I don't need. 
Perharps it's linked ?
I tried to unfreeze and update all the Google apps but the Osm Contributor beta2 still crash at launch.
Other ideas ? What dependencies I can check ?

**Comment by Hugoo13** [comment]
It can be usefull. We received some informations about your problem. 
I have no crash on Android 6.0, I'm going to check on your version to see if I have the same problem.
Have you tried to uninstall/install the app in beta2 ?

**Comment by GilBr** [comment]
It's the same after uninstall/install of the beta2. It crash ...
It's not compatible with my Android version ?

**Comment by Hugoo13** [comment]
There is a problem with Android resources file.
I was able to reproduce the problem on a Samsung Tab on Android 4.4.2. I'm working on a solution.

Sorry for the inconvenience.

**Comment by Hugoo13** [comment]
I found the problem and I solved it ! And now tags are visible !
Tested on Android 4.4.2 and Android 6.0.
Like yesterday, the new version will be available in a few hours !

Keep me informed !

**Comment by GilBr** [comment]
\o/ I'll try this evening

**Comment by GilBr** [comment]
It works ! I Can launch the app and edit POI witj the latest version. Thanks a lot ! I can play again ;-)

**Comment by GilBr** [comment]
I've seen some strange behaviour with POI editing but I'll make a new issue for this.
