### ISSUE TITLE
[Discussion] Help on new feature ?

### ISSUE THREAD

**Issue by GilBr** [jawg/osm-contributor#58]
Is it possible to have some explanations about new feature ?
Like the TimePicket widget (how to use),  2D view to "3D" view ... (how to switch).
It'll be easier for testing ;-)

**Comment by tommybuonomo** [comment]
Hi @GilBr,
The TimePicker widget is using to enter easily some opening periods for a POI. 

For example, type 'Feb-Mar: Mo-Tu 11:00-20:00, We-Th 11:00-14:00, Fr 11:00-18:00, Sa 11:00-19:00; Apr-May, Jul: We-Th 11:00-15:00, Fr 07:00-08:00, Sa 07:00-19:00;' on a Android keyboard is not a good idea.. With the widget, you can easily express this kind of stuff:

![osm1](https://cloud.githubusercontent.com/assets/15737675/18046055/55c4966e-6dd6-11e6-8828-1e7031a704ac.png)

**Comment by GilBr** [comment]
Thanks a lot for the TimePicker widget.
And about the "3D" view ? Sometimes I switch from 2D view to "3D" view but I don't know how ...

**Comment by GilBr** [comment]
It's not this kind of 3D I wanted to talk (my phone doesn't support).
When the app start, it's in 2D (without inclination) but sometimes when the app is still on background and I relauch it, the 2D come with "inclination" (I haven't the good words ...).
We can see it on the annoncement tweet : 
* Normal 2D : 
![osm-contrib1](https://cloud.githubusercontent.com/assets/21213907/18050486/1d26f518-6def-11e6-80a8-7315d85d4b42.PNG)
* 2D with "inclination" : 
![osm-contrib2](https://cloud.githubusercontent.com/assets/21213907/18050499/382e324a-6def-11e6-95f3-3e83ea913a9e.PNG)

But I don't know how to switch between the 2 kind of 2D ...

**Comment by tommybuonomo** [comment]
Ok @GilBr this is called the `tilt` of the map. You can play with it by touching an area with two fingers and dragging both fingers upwards. Drag from top to bottom to return to an overhead view.

**Comment by GilBr** [comment]
Ah yes, tilt view and overhead view + 2 fingers => I've got it
Thanks !

**Comment by tommybuonomo** [comment]
You're welcome @GilBr !
