### ISSUE TITLE
TimePicker widget not shown if opening_hours tag added manually

### ISSUE THREAD

**Issue by GilBr** [jawg/osm-contributor#59]
**Description:**
Perhaps it isn't a bug ... 
With some POI (like restaurant) the TimePicker widget is shown on POI edition.
But if it isn't on the preset, the widget didn't appear.

**Steps and behaviour :**
1. Edit a POI without the opening_hours tag on the preset (like bakery)
2. Add the opening_hours tag 
=> Value edition is in text mode
It's the same when the tag is added on the POI with "Gérer les types de POI" in the expert mode.

**Environment & Version :**
Smartphone : Wiko Rainbow 4G – Android 4.4.2
3.0.0-beta3 + "Preset par défaut" profile + expert mode

**Comment by Hugoo13** [comment]
It's not really a bug. By default, when you create a tag, we set the type to "text". 
We can and we will set the input type if needed !

**Comment by GilBr** [comment]
OK I was not sure. Thanks for your response.
