### ISSUE TITLE
[Bug] Wrong tag and values shown during edition

### ISSUE THREAD

**Issue by GilBr** [jawg/osm-contributor#60]
**Description:**
For some POI, when tags aren't on the preset but values exists for this tag, the editing tool don't show the good tag and values 

**Steps and behaviour :**
1. Select the hotel POI [Residhome Apparthotel](https://www.openstreetmap.org/node/4370012350)
2. Select the "Editer le POI" tool
3. Go the wheelchair tag (the last one)
=> this tag isn't on the preset but exists for the POI on OSM
4. Trying to modify the value of the tag
5. Beds tag is shown (it's the first one for the POI) with values for beds
6. If I edit, beds tags is modified, not the wheelchair tag

I've seen this behaviour on several type of POI, some I have modify with "Gérer les types de POI", some I haven't, like the hotel POI.
I think it's because of tags not on the preset but I'm not sure it's the only reason.

**Environment:**
Smartphone : Wiko Rainbow 4G – Android 4.4.2

**Version:**
3.0.0-beta3 + "Preset par défaut" profile + expert mode

**Comment by GilBr** [comment]
I think there are still problems with tags on the beta4 version. The first tags are shown a 2nd time at the end of the POI list. The amenity tag at the end can be edited but modification aren't saved.

First tags on a post_box POI : 
![screenshot_2016-09-02-20-59-33](https://cloud.githubusercontent.com/assets/21213907/18226605/db9841d8-720d-11e6-9898-63604010ce9b.png)

Last tags : 
![screenshot_2016-09-02-21-00-01](https://cloud.githubusercontent.com/assets/21213907/18226624/4a6b576c-720e-11e6-800d-d20f74785451.png)
In fact operator, amenity, collection_times, ref tags are repeated.
It's on this [POI](https://www.openstreetmap.org/node/3166579562).

**Comment by loicortola** [comment]
Hi GilBr,

thanks for getting back to us (sorry for the delay... SOTM to prepare ;) )
Will look into it today!

**Comment by GilBr** [comment]
It's ok for me with the beta.5 version.
