### ISSUE TITLE
[UX] POI icons on Default View ?

### ISSUE THREAD

**Issue by GilBr** [jawg/osm-contributor#61]
With the 2.0.0 version the default view was with Mapnik. I understand there are many reasons for the Mapbox view on the new version. But I think POI icons are useful in some cases to evaluate if a POI exists or not (without downloading).
Is it possible the show (some) icons the Mapbox view ?
Is it possible to propose a Mapnik view (like the satellite view) ?

**Version:**
3.0.0-beta3 + "Preset par défaut" profile + expert mode

**Comment by loicortola** [comment]
Thanks for the issue!
Mapnik view will be available in expert mode only,
Satellite view is already available for everyone

**Comment by GilBr** [comment]
Thanks !
