### ISSUE TITLE
Save map position, thus it can be restored after app re-start

### ISSUE THREAD

**Issue by stephan75** [jawg/osm-contributor#62]
When OSM contributor app gets terminated by user or by Android system,
map position is always in Paris.

And I often use apps like OSM contributor or other editors without GPS signal.

I would appreciate when the map position is stored somewhere and restored on new app start.

**Comment by loicortola** [comment]
Hi @stephan75 ,

thanks for the feature request. Should be easy to add for the next milestone. Stay tuned!

**Comment by GilBr** [comment]
:+1
