### ISSUE TITLE
Save zoom level after POI edition

### ISSUE THREAD

**Issue by GilBr** [jawg/osm-contributor#63]
**Description:**
After POI edition, zoom level on the map go back the level 16

**Steps to reproduce:**
1. Zoom to level 18 on the map
2. Select a POI
3. Modify a tag + validate modification
4. Zoom go back to the level 16
=> it's the same behaviour if I don't validate the edit

**Expected behavior:**
It would be more convenient if the zoom stay at the same level.
When there are a lot POI shown, I've to zoom again to correctly select another one.

For example in this case : 
![screenshot_2016-09-02-21-43-25](https://cloud.githubusercontent.com/assets/21213907/18226715/3d57e4ee-7210-11e6-94a7-5df98a7b0b6c.png)

**Environment:**
Smartphone : Wiko Rainbow 4G – Android 4.4.2

**Version:**
3.0.0-beta4 + "Preset par défaut" profile + expert mode

**Comment by loicortola** [comment]
Will discuss this with the team as it is a UX issue and not especially a bug.
I think your point makes sense :)

**Comment by GilBr** [comment]
It's OK for me with the beta.5 version. Thanks !
