### ISSUE TITLE
Interest of the duplicate tool ?

### ISSUE THREAD

**Issue by GilBr** [jawg/osm-contributor#65]
**Description:**
I've tried the "Duplicate POI" tool that appears with POI selection. It's ok but only the POI is duplicated, not the values of the tags. This behaviour, for me, isn't really interesting.
What is the added value compared to the "Add POI" tool ?

**Environment:**
Smartphone : Wiko Rainbow 4G – Android 4.4.2

**Version:**
3.0.0-beta4 + "Preset par défaut" profile + expert mode

**Comment by Hugoo13** [comment]
Hey !

It's a shortcut to create a little bit faster a POI.
You can use this feature, for example, if you want to add multiple bus stop, you can duplicate the previous POI without going to the full list. Informations are not duplicated. We thought it wasn't logical to duplicate some tags values (like name).

**Comment by GilBr** [comment]
Hum ok, I understand. But for me it's the same than choosing the tag in the list. The last used are shown at the top, so it's easy to find them ... The name should not be duplicated but for other values, it could be interesting, for example with bicycle_parking.
