### ISSUE TITLE
[Bug] Can't edit existing value on Name tag

### ISSUE THREAD

**Issue by GilBr** [jawg/osm-contributor#66]
**Description:**
When the Name tag is already set and you modify it, modifications aren't saved after POI change validation.

**Steps to reproduce:**
1. Select a POI (like restaurant)
2. Select the Name tag
3. Modify the value and Validate
=> Modification is shown
4. Validate the POI modification
=> Modication is lost (old value is shown)

There's no problem when the Name tag is not set. It's possible to set a value and record it.

**Environment:**
Smartphone : Wiko Rainbow 4G – Android 4.4.2

**Version:**
3.0.0 + "Preset par défaut" profile + expert mode

**Comment by GilBr** [comment]
I've the same problem with Capacity tag on the Bicycle_Parking POI. It's ok when I create the POI, but the value can't be modified on an existing POI with value already set.

**Comment by Hugoo13** [comment]
Should be fixed in next release in few days :)
