### ISSUE TITLE
Information error on save message

### ISSUE THREAD

**Issue by GilBr** [jawg/osm-contributor#68]
**Description:**
After saving POI modifications a message is shown. There's an error with the number, a **%1$s** chain replace it. The message is the same whatever the number of modifications saved.

![screenshot_2016-10-01-18-47-02_cr](https://cloud.githubusercontent.com/assets/21213907/19112273/31c6f1a8-8b04-11e6-9ca8-9f21416f1eb6.png)

**Environment:**
Smartphone : Wiko Rainbow 4G – Android 4.4.2
**Version:**
3.0.0 + "Preset par défaut" profile + expert mode

**Comment by Hugoo13** [comment]
Should also be fixed in next release !
