### ISSUE TITLE
Attach APK on your release

### ISSUE THREAD

**Issue by kosssi** [jawg/osm-contributor#72]
**Description:**
I would like download your APK but I don't have google play. Can you upload APK on your last release?

Like this https://github.com/cozy/cozy-mobile/releases

Thanks

**Comment by Hugoo13** [comment]
Sorry for the delay ! You can get your APK from Github now : 
[https://github.com/jawg/osm-contributor/releases/tag/v3.0.1](https://github.com/jawg/osm-contributor/releases)

**Comment by kosssi** [comment]
👍 thanks
