### ISSUE TITLE
Missing 'created_by' tag in changesets

### ISSUE THREAD

**Issue by polarbearing** [jawg/osm-contributor#73]
Editor software should add a ```created_by``` tag when saving a Changeset.
https://wiki.openstreetmap.org/wiki/Key:created_by

This is important so we can trace bugs in changesets caused by a particular editing software and version. 

A user claims in http://www.openstreetmap.org/changeset/45186979 that he/she was using this software. 

As I cannot find the string ```created_by``` in this repository, I assume the problem is valid.

**Comment by loicortola** [comment]
Hi @polarbearing , 
thanks for the issue. 
Do you suggest we add created_by: osm_contributor ?
If yes, I thought it was in already but I was wrong.
Will change it asap, thanks a lot!

**Comment by polarbearing** [comment]
Not with a colon. 
```created_by``` should be the key, and the value should be ```OSM Contributor VERSION```, you could also add the platform like Android etc.

**Comment by loicortola** [comment]
Yes, that's what I meant (key:value).
Platform doesn't make sense as OSM Contributor is only present on Android.
As we are not collecting ANY user data, I wont vote for a user-related data to be added to any tag.

Consider this as done for the next-release. No ETA on its availability yet as we are currently rushing through new features :)

Will let you know!

**Comment by Hugoo13** [comment]
Available in next release :)

<img width="328" alt="capture d ecran 2017-02-02 a 10 51 15" src="https://cloud.githubusercontent.com/assets/3592767/22544556/9338a618-e935-11e6-9212-bb1a0214e4ff.png">

**Comment by polarbearing** [comment]
Cool. Cannot see the commit yet?
