### ISSUE TITLE
Validate changesets before upload: avoid empty keys and value

### ISSUE THREAD

**Issue by polarbearing** [jawg/osm-contributor#74]
Editor software should perform validity checks on data uploaded to OSM.

A user claims in http://www.openstreetmap.org/changeset/45186979 that he/she was using this software.  There is no created_by string in the changeset, see #73, so we do not know the version.

This changeset contained a key with an empty value, that should be prevented by the editor software, along with stripping leading and trailing spaces in both key and value.

**Comment by loicortola** [comment]
@Hugoo13 , thoughts about that?

**Comment by Hugoo13** [comment]
Should be fixed in next release. :)
