### ISSUE TITLE
Cannot connect anymore

### ISSUE THREAD

**Issue by bagage** [jawg/osm-contributor#80]
**Description:**
Even though the app says "Login successful", I ended up being not connected and I cannot upload any change.

**Steps to reproduce:**

1. Download application from Play store
2. Open it, go to Settings -> Login with Google
3. Google popup appears, enter credentials, validate
4. Popup closes, toast appears "Connection successful"

edit: even the manual login method fails. So it's not specific to Login with Google.

**Expected behavior:**
I should be logged in.

**Actual behavior:**
Whenever I try to submit a change, the application says that I'm missing credentials.

**Stacktrace (If it's a crash):**
```
------------------->  D  ---> HTTP GET http://www.openstreetmap.org/api/0.6/permissions?oauth_con
                                  sumer_key=undefined&oauth_nonce=*XXXXX*&oauth_signature=*XXXX*&oauth_signature_method=HMAC-SHA1&oauth_timestamp=149304
                                  1100&oauth_token=undefined&oauth_version=1.0
------------------->  D  ---> END HTTP (no body)
------------------->  D  <--- HTTP 200 http://www.openstreetmap.org/api/0.6/permissions?oauth_con
                                  sumer_key=undefined&oauth_nonce=4af5f6&oauth_signature=*XXXXX*&oauth_signature_method=HMAC-SHA1&oauth_timestamp=149304
                                  1100&oauth_token=undefined&oauth_version=1.0 (283ms)
------------------->  D  Date: Mon, 24 Apr 2017 13:38:20 GMT
------------------->  D  Server: Apache/2.4.18 (Ubuntu)
------------------->  D  Cache-Control: max-age=0, private, must-revalidate
------------------->  D  Vary: Origin,Accept-Encoding
------------------->  D  X-Permitted-Cross-Domain-Policies: none
------------------->  D  X-XSS-Protection: 1; mode=block
------------------->  D  X-Request-Id: WP3-zH8AAQEAAEfMFS4AAACU
------------------->  D  X-Download-Options: noopen
------------------->  D  X-Runtime: 0.016059
------------------->  D  X-Frame-Options: sameorigin
------------------->  D  X-Content-Type-Options: nosniff
------------------->  D  X-Powered-By: Phusion Passenger 5.1.2
------------------->  D  ETag: W/"XXXXXX-gzip"
------------------->  D  Status: 200 OK
------------------->  D  Keep-Alive: timeout=5, max=100
------------------->  D  Connection: Keep-Alive
------------------->  D  Content-Type: application/xml; charset=utf-8
------------------->  D  OkHttp-Selected-Protocol: http/1.1
------------------->  D  OkHttp-Sent-Millis: 1493041100582
------------------->  D  OkHttp-Received-Millis: 1493041100714
------------------->  D  <?xml version="1.0" encoding="UTF-8"?>
------------------->  D  <osm version="0.6" generator="OpenStreetMap Server">
------------------->  D    <permissions>
------------------->  D    </permissions>
------------------->  D  </osm>
------------------->  D  <--- END HTTP (132-byte body)
```

**Environment:**
Android 7.1.1, LineageOS.

**Version:**
V3.0.1

**Comment by bagage** [comment]
It seems you renamed application package. So Playstore version is stuck to 3.0.1 while you are actually at 3.0.4.
Please consider making a 3.0.2 version of the old package, warning users that they must install the new one instead!

**Comment by bagage** [comment]
edit: It actually doesn't work either with the new version. Cannot login at all with manual user/password, and Google authentication shows "Connection succeeded" toast but I still get an error when I try to upload some changes.
Hopefully you'll fix it anytime :).

**Comment by loicortola** [comment]
Hi @bagage ,
thanks a lot for the test. Sorry for the response delay.
This is really blocking, we will try to fix that.
@PanierAvide any availability to work on that?

The login part we had done was purely and simply a hack: we parsed the OpenStreetMap.org page and manually submitted the registration forms. If those changed then we simply need to patch the flow.

@bagage have you tried with a classic OpenStreetMap account? (Gmail login is simply an alternative). This might help with the debugging.

**Comment by PanierAvide** [comment]
> @PanierAvide any availability to work on that?
Not really, I will be very busy during this week.

**Comment by bagage** [comment]
@loicortola manual authentication doesn't work either, I receive an empty permissions set:

```
<osm version="0.6" generator="OpenStreetMap Server">
  <permissions>
  </permissions>
</osm>
```

**Comment by loicortola** [comment]
Thanks for the info...
I will try to reach out to the french dev community see if they can give us a hand on this matter...

**Comment by bagage** [comment]
Fixed via #84, waiting for the release now :).

**Comment by loicortola** [comment]
Release will be made today :)

**Comment by loicortola** [comment]
Still not working somehow with Gmail Auth.

**Comment by loicortola** [comment]
See #93 for work in progress

**Comment by bagage** [comment]
Manual authentication is working - closing this one since #93 is handling the rest.
