### ISSUE TITLE
How to build a profile

### ISSUE THREAD

**Issue by CorentinLemaitre** [jawg/osm-contributor#82]
Hello,
I try the bike profile it is really powerfull! i am interested to get it better or build other preset. I have seen that there is some widget to make the choice easy for users. I try expert mode but there is no possibility to use widget or share your preset beetween devices. 
My question is : how to build a profile or preset ?

Thanks for the answer,

**Comment by loicortola** [comment]
Hello Corentin,Thanks for the feedback!All profiles are hosted and open for contributions on https://github.com/jawg/h2geo-presetsLet me know if you need any help, everything should be pretty straightforward from there.Le 1 mai 2017 3:58 PM, CorentinLemaitre <notifications@github.com> a écrit :Hello,
I try the bike profile it is really powerfull! i am interested to get it better or build other preset. I have seen that there is some widget to make the choice easy for users. I try expert mode but there is no possibility to use widget or share your preset beetween devices.
My question is : how to build a profile or preset ?
Thanks for the answer,

**Comment by CorentinLemaitre** [comment]
I will try that.
Thanks!
