### ISSUE TITLE
[JungleBus] Preset: Implement transport-v2 model and create related h2geo-preset

### ISSUE THREAD

**Issue by loicortola** [jawg/osm-contributor#88]

**Comment by overflorian** [comment]
Today the tag amenity=bus_stop is a bus stop.
Add also the tag public_transport=platform for the same object

**Comment by overflorian** [comment]
Please do not take into account my previous message.

Here is the definition of a bus stop. There is two possibilities:
-All the nodes taggued public_transport = platform AND bus = yes
OR
-All the nodes tagged highway=bus_stop BUT NOT public_transport = stop_position

When creating a new bus stop, the app should use the following tags:
-highway=bus_stop
AND
-public_transport = platform
AND
-bus = yes

Thanks

**Comment by overflorian** [comment]
As discussed the fix did'nt work. Please fix it according to the overpass query Noemie sent.
Once done we can release a new version! Thanks
