### ISSUE TITLE
[JungleBus] New widget for visual editing of a POI

### ISSUE THREAD

**Issue by overflorian** [jawg/osm-contributor#92]
Implement new widgets to provide a friendlyer editing environment.
TODO: will be detailled later by @overflorian

**Comment by overflorian** [comment]
These new widgets display visual choices instead of regular forms.
This idea comes from the mobile app Street Complete https://github.com/westnordost/StreetComplete

First type of screen could be the kind of bus stops:
Label of the widget >Type d'arrêt de bus
Possible choices >Non indiqué sur terrain (informel) - Poteau indicateur - Abris-bus

Size of the pictures should be defined first. Then the visuals will be provided by @overflorian

**Comment by nicolasfavier** [comment]
@overflorian For picture size the best would be vectoriel images like .svg
If you don't have this kind of picture I think a minimum of 250px is required

**Comment by overflorian** [comment]
Thanks, I will provide the pictures when they'll be needed.

**Comment by overflorian** [comment]
Here are the pictures in svg/png for the button of the first new widget to implement: 
[pictos type d'arrêt de bus.zip](https://github.com/jawg/osm-contributor/files/1454310/pictos.type.d.arret.de.bus.zip).
The grey ones mean the button is turned OFF and the blue one is ON.

Here are the available options:
-all the buttons are OFF: no data is available

-Button 1 (the man alone) is ON: the object has is tagged **"unofficial=yes"**.
If the button is OFF and the user clicks on it, add this tag to the object.

-Button 2 (the man with the pole) is ON: the object has is tagged **"shelter=no"**.
If the button is OFF and the user clicks on it, add this tag to the object.

-Button 3 (the man with the shelter) is ON: the object has is tagged **"shelter=yes"**.
If the button is OFF and the user clicks on it, add this tag to the object.

-it's not possible to switch to ON more than 1 button (same behaviour than radio button)

Once this new widget is implemented, please remove the current "shelter" widget that will become irrelevant.
Thanks guys!

**Comment by overflorian** [comment]
I just updated the last message so it's now correct and I guess you guys have all the info to work on this topic. Thanks

**Comment by overflorian** [comment]
Here an update of the pictures for a better readability: 
[Picto arrêts de bus V2.zip](https://github.com/jawg/osm-contributor/files/1507478/Picto.arrets.de.bus.V2.zip)

**Comment by overflorian** [comment]
Here an update of the pictures, squared version 180x180px
[Pictos V3.zip](https://github.com/jawg/osm-contributor/files/1568373/Pictos.V3.zip)
